// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourNextTravel.Api.Infrastructure.Persistence;

#nullable disable

namespace YourNextTravel.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("YourNextTravel.Api.Domain.Budget.BudgetEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssumptionsNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationSearchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LodgingComponentAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MiscDailyComponentAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationSearchId")
                        .IsUnique();

                    b.ToTable("BudgetEstimates");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Budget.CountryCostIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(6, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("CountryCostIndexes");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Destinations.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Destinations.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("IsoCode2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode2")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Destinations.DestinationSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelerProfileTypeUsed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("DestinationSearches");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Events.EventListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Category", "StartUtc");

                    b.HasIndex("ProviderName", "ExternalId")
                        .IsUnique();

                    b.ToTable("EventListings");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.LegalHealth.LegalHealthRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherHealthNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaccinationRequirementText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisaRequirementText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("LegalHealthRequirements");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Pricing.CurrencyRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyCode", "QuoteCurrencyCode", "AsOfDate")
                        .IsUnique();

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Pricing.LodgingPriceEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgNightlyAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxNightlyAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinNightlyAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("SampleWindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SampleWindowStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "FetchedAtUtc");

                    b.ToTable("LodgingPriceEstimates");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Users.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Category", "Detail")
                        .IsUnique();

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Users.TravelerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TravelerProfiles");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique()
                        .HasFilter("[GoogleSubjectId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Weather.WeatherSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AvgTempC")
                        .HasColumnType("REAL");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ForDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Granularity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxTempC")
                        .HasColumnType("REAL");

                    b.Property<double>("MinTempC")
                        .HasColumnType("REAL");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Granularity", "ForDate");

                    b.HasIndex("CityId", "Granularity", "Month");

                    b.ToTable("WeatherSnapshots");
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Budget.BudgetEstimate", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.DestinationSearch", null)
                        .WithOne()
                        .HasForeignKey("YourNextTravel.Api.Domain.Budget.BudgetEstimate", "DestinationSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Budget.CountryCostIndex", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Destinations.City", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Destinations.DestinationSearch", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YourNextTravel.Api.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Events.EventListing", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.LegalHealth.LegalHealthRequirement", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Pricing.LodgingPriceEstimate", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Users.Interest", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Users.TravelerProfile", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("YourNextTravel.Api.Domain.Users.TravelerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNextTravel.Api.Domain.Weather.WeatherSnapshot", b =>
                {
                    b.HasOne("YourNextTravel.Api.Domain.Destinations.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
